In [ ]:
import pandas as pd

import numpy as np

In [ ]:
pip install --upgrade xgboost scikit-learn


In [ ]:
pip install -U scikit-learn==1.6.1


In [ ]:
# pip install -U scikit-learn==1.2.2


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


DATA LOADING


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/AgriAi final hackthon/final_dataset.csv')

In [ ]:
df

Unnamed: 0  Temparature  Humidity  Moisture  Soil_Type  Crop_Type  \
0             0           20        83        26          0        0.0   
1             1           25        84        32          1        0.0   
2             2           33        64        50          1        1.0   
3             3           34        65        54          1        1.0   
4             4           38        72        51          1        1.0   
..          ...          ...       ...       ...        ...        ...   
133         133           28        54        47          4       14.0   
134         134           24        91        34          4       16.0   
135         135           23        93        31          4       16.0   
136         136           12        95        42          4       16.0   
137         137           27        80        31          0       15.0   

     Nitrogen  Potassium  Phosphorous  Fertilizer  
0          90         49           36           0  
1          66         59           36           0  
2          41          0            0           0  
3          38          0            0           0  
4          39          0            0           0  
..        ...        ...          ...         ...  
133         5         18           15          12  
134        22         17            5          13  
135         4         23            5          13  
136        11         14            5          13  
137        19         21            6          13  

[138 rows x 10 columns]

In [ ]:
duplicates = df.duplicated()
print(duplicates)

0      False
1      False
2      False
3      False
4      False
       ...  
133    False
134    False
135    False
136    False
137    False
Length: 138, dtype: bool


In [ ]:
df=df.drop_duplicates()

In [ ]:
df

Unnamed: 0  Temparature  Humidity  Moisture  Soil_Type  Crop_Type  \
0             0           20        83        26          0        0.0   
1             1           25        84        32          1        0.0   
2             2           33        64        50          1        1.0   
3             3           34        65        54          1        1.0   
4             4           38        72        51          1        1.0   
..          ...          ...       ...       ...        ...        ...   
133         133           28        54        47          4       14.0   
134         134           24        91        34          4       16.0   
135         135           23        93        31          4       16.0   
136         136           12        95        42          4       16.0   
137         137           27        80        31          0       15.0   

     Nitrogen  Potassium  Phosphorous  Fertilizer  
0          90         49           36           0  
1          66         59           36           0  
2          41          0            0           0  
3          38          0            0           0  
4          39          0            0           0  
..        ...        ...          ...         ...  
133         5         18           15          12  
134        22         17            5          13  
135         4         23            5          13  
136        11         14            5          13  
137        19         21            6          13  

[138 rows x 10 columns]

ENCODING THE COLUMNS



In [ ]:
# from sklearn.preprocessing import LabelEncoder

In [ ]:
# cat_cols=['Soil_Type','Crop_Type','Fertilizer']

In [ ]:
# encoder ={}
# for col in cat_cols:
#   le = LabelEncoder()
#   df[col] = le.fit_transform(df[col])
#   encoder[col] = le
# ++

In [ ]:
df

Unnamed: 0  Temparature  Humidity  Moisture  Soil_Type  Crop_Type  \
0             0           20        83        26          0        0.0   
1             1           25        84        32          1        0.0   
2             2           33        64        50          1        1.0   
3             3           34        65        54          1        1.0   
4             4           38        72        51          1        1.0   
..          ...          ...       ...       ...        ...        ...   
133         133           28        54        47          4       14.0   
134         134           24        91        34          4       16.0   
135         135           23        93        31          4       16.0   
136         136           12        95        42          4       16.0   
137         137           27        80        31          0       15.0   

     Nitrogen  Potassium  Phosphorous  Fertilizer  
0          90         49           36           0  
1          66         59           36           0  
2          41          0            0           0  
3          38          0            0           0  
4          39          0            0           0  
..        ...        ...          ...         ...  
133         5         18           15          12  
134        22         17            5          13  
135         4         23            5          13  
136        11         14            5          13  
137        19         21            6          13  

[138 rows x 10 columns]

DATA PREPROCESSING



In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.iloc[:,1:9]
y=df.iloc[:,-1]

In [ ]:
x

Temparature  Humidity  Moisture  Soil_Type  Crop_Type  Nitrogen  \
0             20        83        26          0        0.0        90   
1             25        84        32          1        0.0        66   
2             33        64        50          1        1.0        41   
3             34        65        54          1        1.0        38   
4             38        72        51          1        1.0        39   
..           ...       ...       ...        ...        ...       ...   
133           28        54        47          4       14.0         5   
134           24        91        34          4       16.0        22   
135           23        93        31          4       16.0         4   
136           12        95        42          4       16.0        11   
137           27        80        31          0       15.0        19   

     Potassium  Phosphorous  
0           49           36  
1           59           36  
2            0            0  
3            0            0  
4            0            0  
..         ...          ...  
133         18           15  
134         17            5  
135         23            5  
136         14            5  
137         21            6  

[138 rows x 8 columns]

In [ ]:
y

0       0
1       0
2       0
3       0
4       0
       ..
133    12
134    13
135    13
136    13
137    13
Name: Fertilizer, Length: 138, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


In [ ]:
y_train=np.array(y_train).ravel()
y_train

array([ 0, 11,  5,  0, 12,  6,  6, 13, 12,  0, 11,  8,  4,  0,  5, 11,  7,
        5,  0, 10,  3,  0,  5, 12,  8,  5,  1,  6, 12,  0,  1, 10,  0,  7,
        5,  1,  5,  6,  5,  0,  6,  6,  5,  2,  2,  7,  0,  5,  6,  6, 10,
       12,  0,  0,  8,  0,  0,  3,  6, 10,  0,  7, 11, 10,  5,  5,  7,  5,
        7,  5, 13,  6, 10,  7,  5,  5,  7,  5,  7, 10, 10,  5,  6,  1, 12,
        5,  5, 10,  3,  1,  9, 12,  0,  5,  0,  0,  0,  8,  8, 10,  7,  6,
       10, 13,  0,  6,  9,  0,  7,  8])

IMPLEMENTATION OF MODEL (XGB BOOST)

In [ ]:
import xgboost as xgb

In [ ]:
from xgboost import XGBClassifier

y_train = np.ravel(y_train)



In [ ]:
model1 = xgb.XGBClassifier(n_estimators=100,learning_rate=0.1,max_depth=5,random_state=42)

In [ ]:
y_train

array([ 0, 11,  5,  0, 12,  6,  6, 13, 12,  0, 11,  8,  4,  0,  5, 11,  7,
        5,  0, 10,  3,  0,  5, 12,  8,  5,  1,  6, 12,  0,  1, 10,  0,  7,
        5,  1,  5,  6,  5,  0,  6,  6,  5,  2,  2,  7,  0,  5,  6,  6, 10,
       12,  0,  0,  8,  0,  0,  3,  6, 10,  0,  7, 11, 10,  5,  5,  7,  5,
        7,  5, 13,  6, 10,  7,  5,  5,  7,  5,  7, 10, 10,  5,  6,  1, 12,
        5,  5, 10,  3,  1,  9, 12,  0,  5,  0,  0,  0,  8,  8, 10,  7,  6,
       10, 13,  0,  6,  9,  0,  7,  8])

In [ ]:
print("Final y_train:", np.unique(y_train))
print("Final y_test:", np.unique(y_test))
print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)


Final y_train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
Final y_test: [ 0  1  2  5  6  7  8  9 10 13]
x_train shape: (110, 8)
y_train shape: (110,)


In [ ]:
model1.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [ ]:
print(x_train.dtypes)


Temparature      int64
Humidity         int64
Moisture         int64
Soil_Type        int64
Crop_Type      float64
Nitrogen         int64
Potassium        int64
Phosphorous      int64
dtype: object


In [ ]:
y_test=y_test.ravel()

<ipython-input-78-0e2abd030984>:1: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  y_test=y_test.ravel()


In [ ]:
model1.score(x_test,y_test)

0.75

In [ ]:
print("x_train shape:", y_train.shape)
print("x_test shape:", y_test.shape)


x_train shape: (110,)
x_test shape: (28,)


PREDCITION TESTING


In [ ]:
#

IMPLEMENTATION OF ALGO(RANDOM FOREST)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model2=RandomForestClassifier(n_estimators=100,random_state=42,max_depth=5)

In [ ]:
model2.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [ ]:
model2.score(x_test,y_test)

0.7857142857142857

In [ ]:
import joblib

In [ ]:
model2.predict([[20,83,26,0,0,90,49,36]])


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
feature_names = model2.feature_names_in_

In [ ]:
feature_names

array(['Temparature', 'Humidity', 'Moisture', 'Soil_Type', 'Crop_Type',
       'Nitrogen', 'Potassium', 'Phosphorous'], dtype=object)

In [ ]:
input_data = pd.DataFrame([[26, 82, 25, 1, 0, 86, 41, 36]], columns=feature_names)

In [ ]:
prediction = model2.predict(input_data)

In [ ]:
import pickle

In [ ]:
joblib.dump(model2, 'mdl_fr_v5.pkl')

['mdl_fr_v5.pkl']

In [ ]:
print(model2.n_classes_)  # Should show the number of unique classes
print(model2.feature_importances_)  # Should show nonzero values


14
[0.05704904 0.10221597 0.05052214 0.02742096 0.06642614 0.25858944
 0.15691094 0.28086538]


In [ ]:
prediction

array([1])

In [ ]:
pip install streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 45.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 41.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 3.1 MB/s eta 0:00:00


K FOLDCROSS VALIDATION

In [ ]:
from sklearn.model_selection import KFold, cross_val_score

In [ ]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

In [ ]:
model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)

In [ ]:
cv_scores = cross_val_score(model, x, y, cv=kf, scoring='accuracy')

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
1 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    X=X,
        ^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py", line 1559, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [ 0  1  2  3  4  5  6  7  8

In [ ]:
print("Cross-Validation Scores:", cv_scores)
print("Mean Accuracy:", np.mean(cv_scores))
print("Standard Deviation:", np.std(cv_scores))

Cross-Validation Scores: [0.75              nan 0.75       0.77777778 0.77777778]
Mean Accuracy: nan
Standard Deviation: nan


In [ ]:
print("Any NaN values in X:", np.isnan(x).sum())
print("Any NaN values in y:", np.isnan(y).sum())


Any NaN values in X: Temparature    0
Humidity       0
Moisture       0
Soil_Type      0
Crop_Type      0
Nitrogen       0
Potassium      0
Phosphorous    0
dtype: int64
Any NaN values in y: 0
